config/sidekiq_cron.yml
They were overwriting one another
=> Name eth and btc jobs for unconfirmed tx sync differently

app/services/eth/save_block_info.rb, spec/services/eth/save_block_info_spec.rb
If current block is 200, and the block we're syncing is 200, we have 1 confirmation
=> Fix the confirmation computation of ether blocks

config/initializers/message_bus.rb
MessageBus by default retains up to 100 million messages up to 10 days
=> Increase MessageBus data retention

app/services/btc/check_txs.rb, app/services/btc/delete_forked_block.rb, app/services/btc/get_blocks_to_sync.rb, app/services/btc/save_block_info.rb, app/services/btc/set_blocks.rb, app/services/btc/sync_block.rb, app/services/eth/check_txs.rb, app/services/eth/delete_forked_block.rb, app/services/eth/get_blocks_to_sync.rb, app/services/eth/save_block_info.rb, app/services/eth/set_blocks.rb, app/services/eth/sync_block.rb, spec/fixtures/vcr_cassettes/Eth_CheckTxs/enqueues_blocks_to_sync.yml, spec/services/btc/delete_forked_block_spec.rb, spec/services/btc/get_blocks_to_sync_spec.rb, spec/services/btc/save_block_info_spec.rb, spec/services/btc/set_blocks_spec.rb, spec/services/eth/check_txs_spec.rb, spec/services/eth/delete_forked_block_spec.rb, spec/services/eth/get_blocks_to_sync_spec.rb, spec/services/eth/save_block_info_spec.rb, spec/services/eth/set_blocks_spec.rb
Rely on an action to pass the scope of blocks that the rest of the actions will work with. Less prone to scoping issues.
=> Refactor block scopes

app/services/eth/get_blocks_to_sync.rb
https://ethereum.stackexchange.com/questions/319/what-number-of-confirmations-is-considered-secure-in-ethereum
150 is closer to 250 (in the discussion above). Seems like a reasonable amount for now
=> Sync eth blocks up to 150 confs

app/services/notify_tx_receipt.rb
This reverts commit 647b3dcbc96568177708715fe41788b87cdda843.
Discussion: https://github.com/bloom-solutions/crypto-cold-store/pull/37
=> Revert "Add last_id in NotifyTxReceipt data params"

app/jobs/sync_missing_blocks_job.rb, app/models/block.rb, app/services/detect_block_gaps.rb, app/services/sync_missing_blocks.rb, spec/jobs/sync_missing_blocks_job_spec.rb, spec/models/block_spec.rb, spec/services/detect_block_gaps_spec.rb, spec/services/sync_missing_blocks_spec.rb
For whatever reason, if the normal `CheckTxs` services miss a block, this is what we can run to recover from missing blocks.
This will be run on a schedule, probably every day. The schedule isn't included yet as performance tests will need to be performed on staging before we automate it.
=> Add job and services to sync missing blocks

Gemfile.lock, app/lib/btc/address_generator.rb
Use newer version of btcruby that auto-generates the testnet multisig address if testnet extended keys are given
=> Fixes generation of testnet multisig addresses

app/services/notify_tx_receipt.rb, spec/services/notify_tx_receipt_spec.rb
No need to do the extra work. Allow clients to accept JSON and not have to parse it.
=> Publish data as JSON and not a string

app/jobs/btc/sync_block_job.rb, app/jobs/eth/sync_block_job.rb, config/sidekiq.yml, config/sidekiq_cron.yml
So that a rush of jobs of one coin won't heavily affect the other coins
=> Enqueue into coin specific queues

app/services/btc/get_remote_blocks.rb
10 blocks takes about 12 seconds in the few calls made to test. When the system lags for whatever reason and many blocks need to be synced, the bitcoin nodes end up dying because they run out of memory. Instead of spiking the system memory usage a lot, slice up the txs we fetch.
=> Slice up fetching of blocks

app/services/btc/append_output_address.rb, app/services/btc/find_address.rb, app/services/btc/get_output_addresses.rb, app/services/btc/get_remote_tx_output_addresses.rb, app/services/btc/process_remote_txs.rb, app/services/btc/sync_blocks.rb, app/services/btc/sync_unconfirmed_txs.rb, app/services/sync_missing_blocks.rb, spec/fixtures/vcr_cassettes/SyncMissingBlocks/given_btc_param/enqueues_missing_blocks.yml, spec/services/btc/find_address_spec.rb, spec/services/btc/get_output_addresses_spec.rb, spec/services/btc/get_remote_tx_output_addresses_spec.rb, spec/services/btc/process_remote_txs_spec.rb
Problem: going through each bitcoin output address one at a time was making our jobs take about 2 to 3 minutes.
Solution: do a batch search on the output addresses. If one of the addresses that we care about is there, it will then continue and take 2 to 3 minutes to sync up. If there are no addresses there that we care about, then it will skip the rest of the actions. On staging, this task took about 10 ms.
=> Batch search

app/jobs/application_job.rb, spec/jobs/application_job_spec.rb
There are network calls to the the crypto nodes that fail; instead of adding to the number of failed jobs, retry.
=> Retry failed jobs

app/services/eth/get_pending_txs.rb, spec/services/eth/get_pending_txs_spec.rb
- capture `EOFError`
- capture `Net::ReadTimeout`
The issue is intermittent, and it seems like for the `EOFError`, it is somewhere deep in `Net::HTTP`.
=> Fetching txpool content is in a circuit

app/jobs/check_txs_job.rb, app/jobs/sync_missing_blocks_job.rb, app/jobs/sync_unconfirmed_txs_job.rb, spec/jobs/check_txs_job_spec.rb, spec/jobs/sync_missing_blocks_job_spec.rb, spec/jobs/sync_unconfirmed_txs_job_spec.rb
See https://github.com/mhenrixon/sidekiq-unique-jobs/issues/353
Even with the upgrade to 6.0.7, some jobs still get stuck forever.
Since we know the max amount of time certain jobs can take, let's
set an auto expiration time more than the max time. Having it auto
expire will save us from manually deleting the unique digests that
stay longer than they should, but keeping the lock will allow us to
queue jobs more often without duplicating the jobs queued.
Worst case is that we'll wait one minute to check for new txs,
best case is that we will check every 10 seconds.
=> Adjust job lock and expiry time settings

app/services/btc/enqueue_block_hashes_to_sync.rb, app/services/btc/get_blocks_to_sync.rb, app/services/btc/set_blocks.rb, app/services/eth/get_blocks_to_sync.rb, app/services/eth/set_blocks.rb, app/services/sync_missing_blocks.rb, spec/services/btc/enqueue_block_hashes_to_sync_spec.rb, spec/services/btc/get_blocks_to_sync_spec.rb, spec/services/btc/set_blocks_spec.rb, spec/services/eth/get_blocks_to_sync_spec.rb, spec/services/eth/set_blocks_spec.rb
Just in case workers get backed up and a block that is already sufficiently confirmed gets enqueued, remove it from the list of blocks that will be synced.
- Rely on `SetBlocks` to do the screening
- Remove use of `SetBlocks` when syncing missing blocks
=> Double-check that the blocks being synced are less than max confs

app/services/btc/enqueue_block_hashes_to_sync.rb, app/services/btc/get_blocks_to_sync.rb, app/services/btc/set_blocks.rb, app/services/eth/get_blocks_to_sync.rb, app/services/eth/set_blocks.rb, app/services/sync_missing_blocks.rb, spec/services/btc/enqueue_block_hashes_to_sync_spec.rb, spec/services/btc/get_blocks_to_sync_spec.rb, spec/services/btc/set_blocks_spec.rb, spec/services/eth/get_blocks_to_sync_spec.rb, spec/services/eth/set_blocks_spec.rb
Reverts bloom-solutions/crypto-cold-store#102
This breaks creation of blocks that haven't been seen before.
=> Revert "Double-check that the blocks being synced are less than max confs"

app/models/block.rb, app/services/btc/filter_block_hashes.rb, app/services/btc/sync_blocks.rb, spec/models/block_spec.rb, spec/services/btc/filter_block_hashes_spec.rb
In case the jobs are backed up and multiple jobs a job with a recently-synced block had already been enqueued, this will skip it when it is time to sync
=> Only unconfirmed

app/services/eth/check_confirmations.rb, app/services/eth/sync_block.rb, spec/services/eth/check_confirmations_spec.rb
In cases where the jobs get backed up, this will skip jobs whose blocks have already been sufficiently confirmed thus speeding up the process
=> Do not sync Eth blocks that have been sufficiently confirmed

app/jobs/btc/sync_blocks_job.rb, app/jobs/check_txs_job.rb, app/jobs/eth/sync_block_job.rb, app/services/btc/filter_block_hashes.rb, spec/jobs/btc/sync_blocks_job_spec.rb, spec/jobs/check_txs_job_spec.rb, spec/jobs/eth/sync_block_job_spec.rb
Forgot to add force expiration of locks for `Eth` and `Btc` `SyncBlocksJob`
Also: lengthen forced lock expiration for CheckTxsJob
=> Expire btc eth jobs

app/jobs/sync_unconfirmed_txs_job.rb
They end up piling up, even if they shouldn't take more than 1 minute.
=> chore: increase lock time expiration for SyncUnconfirmedTxsJob
